instanceId: "18662347"



http:
  listener:
    host: "0.0.0.0"
    port: "8081"
  requester:
    sms:
      host: "api.authkey.io"
      port: ""
      path: "/request"
    
    


    
        
            
                
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                        
                                                            
                                                                
                                                                    
                                                                        
                                                                            
                                                                                
                                                                                    
                                                                                        
                                                                                            
                                                                                                
                                                                                                    
                                                                                                        
                                                                                                            
                                                                                                                
                                                                                                                    
                                                                                                                        
                                                                                                                            
                                                                                                                                
                                                                                                                                    
                                                                                                                                            
sfdc:
  username: "mulesoftenthusiast@gmail.com"
  password: "Silky12345"
  securityToken: "AFhvGSow32ZWhX331GcMM9my"



