#%RAML 1.0
title: customer-sapi-raml
description: This API is used by PAPI to connect with SFDC
version: 1.0.0

traits:
  common-header : !include /exchange_modules/797e6d10-a70d-4c71-bce4-f7f7e9384939/common-fragment/1.0.1/traits/header-common-trait.raml

  

types:
  error-dataType : !include /exchange_modules/797e6d10-a70d-4c71-bce4-f7f7e9384939/common-fragment/1.0.1/dataTypes/error-dataType.raml
  post-registration-request : !include /exchange_modules/797e6d10-a70d-4c71-bce4-f7f7e9384939/common-fragment/1.0.1/dataTypes/post-registration-request-dataType.raml
  post-registration-response : !include /exchange_modules/797e6d10-a70d-4c71-bce4-f7f7e9384939/common-fragment/1.0.1/dataTypes/post-registration-response-dataType.raml

  post-customer-state-request : !include /exchange_modules/797e6d10-a70d-4c71-bce4-f7f7e9384939/common-fragment/1.0.1/dataTypes/post-customer-state-request-dataType.raml
  post-customer-state-response : !include /exchange_modules/797e6d10-a70d-4c71-bce4-f7f7e9384939/common-fragment/1.0.1/dataTypes/post-customer-state-response-dataType.raml

/customers:
  /registration:
    post:
      is:
        - common-header
      body:
        application/json:
          type: post-registration-request 
          example: !include /examples/post-registration-request-example.json
      responses:
        201:
          body:
            application/json:
              type: post-registration-response
              example: !include /examples/post-registration-response-example.json
                
        400:
          body:
            application/json:
              type: error-dataType
              example: !include /exchange_modules/797e6d10-a70d-4c71-bce4-f7f7e9384939/common-fragment/1.0.1/examples/error-400-response-example.json                    
        401:
          body:
            application/json:
              type: error-dataType
              example: !include /exchange_modules/797e6d10-a70d-4c71-bce4-f7f7e9384939/common-fragment/1.0.1/examples/error-401-response-example.json
        404:
          body:
            application/json:
              type: error-dataType
              example: !include /exchange_modules/797e6d10-a70d-4c71-bce4-f7f7e9384939/common-fragment/1.0.1/examples/error-404-response-example.json
        500:
          body:
            application/json:
              type: error-dataType  
              example: !include /exchange_modules/797e6d10-a70d-4c71-bce4-f7f7e9384939/common-fragment/1.0.1/examples/error-500-response-example.json



/customerState:
    post:
      is:
        - common-header
      body:
        application/json:
          type: post-customer-state-request 
          example: !include /examples/post-customer-state-request-example.json
      responses:
        201:
          body:
            application/json:
              type: post-customer-state-response
              example: !include /examples/post-customer-state-response-example.json
                
        400:
          body:
            application/json:
              type: error-dataType
              example: !include /exchange_modules/797e6d10-a70d-4c71-bce4-f7f7e9384939/common-fragment/1.0.1/examples/error-400-response-example.json                    
        401:
          body:
            application/json:
              type: error-dataType
              example: !include /exchange_modules/797e6d10-a70d-4c71-bce4-f7f7e9384939/common-fragment/1.0.1/examples/error-401-response-example.json
        404:
          body:
            application/json:
              type: error-dataType
              example: !include /exchange_modules/797e6d10-a70d-4c71-bce4-f7f7e9384939/common-fragment/1.0.1/examples/error-404-response-example.json
        500:
          body:
            application/json:
              type: error-dataType  
              example: !include /exchange_modules/797e6d10-a70d-4c71-bce4-f7f7e9384939/common-fragment/1.0.1/examples/error-500-response-example.json
